apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sample-argocd-project
  source:
    repoURL: https://github.com/kenta872/argocd-sample-infra.git
    path: manifests/database
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}