apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-argocd-project
  namespace: argocd
spec:
  description: sample project
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc